spring.application.name=walley

spring.datasource.url=jdbc:postgresql://212.233.89.45:5432/Walley
spring.datasource.username=user
spring.datasource.password=Z1s0L(X4qt12kd344
spring.datasource.driver-class-name=org.postgresql.Driver

#???????????????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true